project_id = "vtnmfpnrpwvclhosjfiq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbuckets]
enabled = true
port = 54324

[functions.send-contact-email]
verify_jwt = false

[analytics]
enabled = false
port = 54327