// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtnmfpnrpwvclhosjfiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0bm1mcG5ycHd2Y2xob3NqZmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTk0NDAsImV4cCI6MjA3MjY3NTQ0MH0.1prRjrUfl8i7OGn3V_y0Bfdz9aPMRvU1v7dys_ptkpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});